server:
  port: 9999
logging:
  level:
    web: info
    root: info
    bts: debug

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    expose-request-attributes: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bu}
  jpa:
    hibernate:
      ddl-auto: none

  security:
    user:
      name: u
      password: u

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - openid
              - email
              - profile
discord:
  key: ${DISCORD_KEY}

host:
  base-url: ${BASE_HOST}