server:
  port: 9999
logging:
  level:
    web: info
    root: info
    bts: debug
spring:

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    expose-request-attributes: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bu}
  jpa:
    hibernate:
      ddl-auto:  update

  security:
    user:
      name: u
      password: u

    oauth2:
      client:
        registration:
          google:
            client-id: 536832065598-pielsep4g4mi8cjir805gldpasru8gff.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - email
              - profile
discord:
  key: "MTEwNjIzNTQwMjA4MTI4ODIxMg.GO3dgn.aDSLkgZTdOgmP65ejVmLlyO5weSVMuC6jUDPRU"

host:
  base-url: "http://localhost:9999"